eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
server:
  port: 8765
  #port: 8760
spring:
  application:
    name: service-feign
feign:
  hystrix:
    enabled: true
